"""add path columns for text memos (brief/memo/report/verdict/finding)

Revision ID: 6720e30902e0
Revises: dc9b8b6ae2d1
Create Date: 2026-04-27 15:52:27.737780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6720e30902e0'
down_revision: Union[str, Sequence[str], None] = 'dc9b8b6ae2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_path', sa.Text(), nullable=True))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memo_path', sa.Text(), nullable=True))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finding_path', sa.Text(), nullable=True))

    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brief_path', sa.Text(), nullable=True))

    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verdict_path', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_column('verdict_path')

    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_column('brief_path')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('finding_path')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('memo_path')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('report_path')

    # ### end Alembic commands ###
